webapp/colemass/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.template import RequestContext
from django.contrib.auth import views as auth_views

from chores.views import mycolemass, stats
from users.views import setup, start, settings

authentication_urls = [
    url(r'^start/$', start, name='start'),
    url(r'^setup/$', setup, name='setup'),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout_then_login, name='logout'),
    url(r'^password-reset/$', auth_views.password_reset, {'post_reset_redirect': 'login'}, name='password_reset'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', auth_views.password_reset_confirm, {'post_reset_redirect': 'login'}, name='password_reset_confirm'),
#    url(r'password_change_done', settings, name='password_change_done')
#    url('^change-password/', auth_views.password_change, {'template_name': 'change-password.html', 'post_change_redirect': '/users/settings/'})
]

urlpatterns = [
    url(r'^$', mycolemass, name="mycolemass"),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^dishes/', include('dishes.urls', namespace="dishes")),
    url(r'^appliances/', include('appliances.urls', namespace="appliances")),
    url(r'^stats/', stats, name="stats"),
    url(r'^chores/', include('chores.urls', namespace="chores")),
    url(r'^user/', include('users.urls', namespace="users")),
    url(r'^hw/', include('hardware.urls', namespace="hardware")),
] + authentication_urls

def handler404(request):
    response = render_to_response('error404.html', {},
                                  context_instance=RequestContext(request))
    response.status_code = 404
    return response


def handler500(request):
    response = render_to_response('error404.html', {},
                                  context_instance=RequestContext(request))
    response.status_code = 500
    return response

def handler403(request):
    response = render_to_response('error404.html', {},
                                  context_instance=RequestContext(request))
    response.status_code = 403
    return response

webapp/users/urls.py
from django.conf.urls import url
from . import views, registrationviews, settingsviews


urlpatterns = [
    url(r'^settings/$', views.settings, name='settings'),
    url(r'^broken_card/$', settingsviews.cardbroken, name='broken_card'),
    url(r'^update_card/$', settingsviews.cardupdate, name='update_card'),
    url(r'^deactivate/$', settingsviews.deactivate, name='deactivate'),
    url(r'^update_email/$', settingsviews.emailupdate, name='update_email'),
    url(r'^newuser/$', settingsviews.newuser, name='newuser'),
    url(r'^change_password/$', settingsviews.change_password, name='change_password'),
    url(r'^change_username/$', settingsviews.change_username, name='change_username'),
    url(r'^register/(?P<user>.*@\w+.\w+)/(?P<valid_key>\w+)/$', registrationviews.createuserform),
    url(r'^registeruser/$', registrationviews.registeruser, name='registeruser'),
    url(r'^set_absent/$', settingsviews.set_absent, name='set_absent'),
    url(r'^set_present/$', settingsviews.set_present, name='set_present'),
    url(r'^come_back/$', settingsviews.come_back, name='come_back'),
]

webapp/users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.core.validators import validate_email
from django.core.exceptions import ValidationError
from chores.models import RecurringChore
from random import randint
from django.contrib.auth.hashers import check_password
import datetime
# These are the models pertaining to USERS and other MANAGEMENT

PASSWORD_SET_LENGTH=4
STEP_CHECK=True
INVITE_TIMEOUT = 120 #seconds

class Card(models.Model):
    key = models.CharField(max_length=14, primary_key=True)
    user = models.OneToOneField(User, blank=True, null=True, unique=True, on_delete=models.SET_NULL)
    is_broken = models.BooleanField(default=False)

    def __str__(self):
        return self.key

    def is_usable(self):
        return ((not self.is_broken) and bool(self.user))


class UserDetail(models.Model):
    user = models.OneToOneField(User, primary_key=True)
    valid_key = models.CharField(max_length=32, blank=True, null=True, default=None)
    valid_key_time = models.DateTimeField(default=timezone.now, blank=True, null=True)
    is_absent = models.BooleanField(default=False)
    is_absent_since = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return ("User detail for %s." % self.user.username)

    def check_validkey(self, valid_key):
        if self.valid_key_time < (timezone.now() - datetime.timedelta(seconds=INVITE_TIMEOUT)):
            self.valid_key = ''
            self.save()
        return (self.valid_key == valid_key)

    def set_absent(self, reason):
        self.is_absent=True
        self.is_absent_since= timezone.now()
        chores= RecurringChore.objects.all()
        for chore in chores:
            if chore.assignee==self.user:
                chore.refuse(reason)
            chore.remove_from_round_robin(self.user)
            chore.save()
        self.save()
        return None

    def set_present(self):
        self.is_absent=False
        self.is_absent_since= timezone.now()
        chores= RecurringChore.objects.all()
        for chore in chores:
            chore.add_randomly_to_round_robin(self.user)
            chore.save()
        self.save()
        return None

    def deactivate(self, reason):
        try:
            self.set_absent(reason)
        except:
            msg='non'
        return None

    def getusername(self):
        return self.user

def validatemail(email):
    try:
        validate_email(email)
        return True
    except:
        return False

def update_password(user, newpswd, oldpswd):
    if len(newpswd)<=PASSWORD_SET_LENGTH:
        return "Error:New Password is too short"
    try:
        user=User.objects.get(username=user)
    except:
        return "Database Connectivity Error: Please Try Again"
    if(check_password(oldpswd, user.password)):
        try:
            user.set_password(newpswd)
            user.save()
            return "Password updated"
        except:
            return "Database Connectivity Error: Please Try Again"
    else:
        return "Error:Password Doesn't Match"

def create_password(user, nwpswd, repswd):
    if len(nwpswd)<=PASSWORD_SET_LENGTH:
        return "Error:Your Password is too short"
    if str(nwpswd)==str(repswd):
        return "Sucess"
    else:
        return "Error:Password Doesn't Match"

def check_email(email):
    if validatemail(email):
        try:
            email_list=User.email.all()
            if email in email_list:
                return False
            else:
                return True
        except:
            return False
    else:
        return False

def check_username(uname):
    try:
        User.objects.get(username=uname)
        return False
    except:
        return True

webapp/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm

from .models import UserDetail, Card

class CreateUserForm(forms.ModelForm):
    email = forms.EmailField(required=True)
    
    class Meta:
        model = User
        fields = ('username', 'email', 'password')

class SelectCardForm(forms.Form):
    user = forms.ModelChoiceField(queryset=User.objects.all())
    card = forms.ModelChoiceField(queryset=Card.objects.filter(user__isnull=True, is_broken=False), required=True)
        
# class UserDefaultForm(forms.ModelForm):
    # username = forms.CharField(required=True)
    # email = forms.EmailField(required=True)

    # class Meta:
        # model = User
        # fields = ("username", "email")
    
    # def clean_username(self):
        # username = self.cleaned_data['username']
        # if username == "default":
            # raise forms.ValidationError("Please choose a username.")
        # return username
        
# class UserPasswordDefaultForm(forms.Form):
    # password = forms.CharField(required=True, widget=forms.PasswordInput)
    # password2 = forms.CharField(required=True, widget=forms.PasswordInput)
    
    # def clean_password2(self):
        # password = self.cleaned_data['password']
        # password2 = self.cleaned_data['password2']
        # if password != password2:
            # raise forms.ValidationError("Passwords do not match.")
        # return password

webapp/users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, Http404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.mail import EmailMessage
from .models import *
from .forms import CreateUserForm, SelectCardForm
#from django.contrib.auth.forms import UserChangeForm, UserCreationForm, SetPasswordForm
import random
import string
# These are the views pertaining to USERS and other MANAGEMENT

def start(request):
    if User.objects.all().count() > 0:
        return redirect('login')
    else:
        return redirect('setup')

def setup(request):
    if User.objects.all().count() > 0:
        return redirect('login')
    elif request.method == 'POST':
        form = CreateUserForm(request.POST)
        try:
            card = Card.objects.get(key=request.POST.get('card_key'))
        except Card.DoesNotExist:
            card = None
            messages.error(request, "The card you have chosen does not exist.")
        if form.is_valid() and card:
            if card.user is not None:
                messages.error(request, "The card you have chose has already been assigned.")
            elif form.cleaned_data['password'] != request.POST.get('password2'):
                messages.error(request, "Passwords do not match.")
            else:
                user = User.objects.create_user(**form.cleaned_data)
                UserDetail.objects.create(user=user)
                card.user = user
                card.save()
                return redirect('login')
        else:
            for error in form.errors.values():
                messages.error(request, error[0])
    else:
        form = CreateUserForm()
    cards = Card.objects.filter(user__isnull=True, is_broken=False)
    return render(request, 'users/setup.html', {'form': form, 'cards': cards})

@login_required
def settings(request):
    cards = Card.objects.filter(user__isnull=True, is_broken=False)
    is_absent= UserDetail.objects.get(user=request.user).is_absent
    return render(request, 'users/settings.html', {'cards': cards, 'is_absent':is_absent})

# def register(request):
    # if request.method == 'POST':
        # password_form = UserPasswordDefaultForm(request.POST)
        # username_form = UserDefaultForm(request.POST)
        # if password_form.is_valid() and username_form.is_valid():
            # username_form.save()
            # username_form.user.set_password(password_form.cleaned_data['password'])
            # username_form.user.save()
            # return redirect('logout')
        # else:
            # for error in password_form.errors.values():
                # messages.error(request, error)
                # password_form = SetPasswordForm(user=request.user)
            # for error in username_form.errors.values():
                # messages.error(request, error)
                # username_form = UserDefaultForm(instance=request.user)
    # else:
        # username_form = UserDefaultForm(instance=request.user)
        # password_form = UserPasswordDefaultForm()
    # return render(request, 'users/default_user.html', {'password_form': password_form, 'username_form': username_form})
        

'''
HARDWARE request
'''
def getcardlist(request):
    s = '<%s>' % ''.join([di['card'] for di in Card.objects.values('card')])
    return HttpResponse(s)

webapp/users/templates/users/register_user.html
{% extends 'registration/base.html' %}
{% block content %}

<form action="{% url 'users:registeruser' %}" method="post" autocomplete="false">
    <input type="hidden" value="{{ csrf_token }}" name="csrfmiddlewaretoken">
    <p class="pawd">Please specify your Username, Name, and password.<br><br>
      <input type="hidden" value="{{ valid_key }}" name="valid_key">
      <input type="hidden" value="{{ user }}" name="oldusename">
      <table>
        <tr>
          <td>Email*:</td><td><input type="text" value="{{ user }}" name="email"></td>
          {% if msgemail %}
            <span style="color: #F00; text-align:left;">{{msgemail}}</span><br><br>
          {% endif %}
        </tr><tr>
          <td>Username*:</td><td><input type="text" name="nwuname" placeholder=" Enter Username" autocomplete="off"></td><br><br>
      {% if msguser %}
        <span style="color: #F00; text-align:left;">{{msguser}}</span><br><br>
      {% endif %}
    </tr><tr>
      <td>First Name:</td><td><input type="text" name="fname" placeholder=" Enter First Name"></td>
      </tr><tr>
      <td>Last Name:</td><td><input type="text" name="lname" placeholder=" Enter Last Name" value="" autocomplete="false"></td>
      </tr><tr>
      <td>Password*:</td><td><input type="password" name="nwpaswd" placeholder=" Enter Password" autocomplete="false"></td>
      </tr><tr>
      <td>Re-enterPassword*:</td><td><input type="password" name="repaswd" placeholder=" Enter Password" autocomplete="false"></td>
      {% if msgpswd %}
        <span style="color: #F00; text-align:left;">{{msgpswd}}</span><br><br>
      {% endif %}
      </tr><tr>
        <select name="card_id">
          {% for car in cards %}
            <option value="{{car.key}}">{{car.key}}</option>
          {% endfor %}
    		</select>
        </tr><tr>
      <td><input type="submit" value="Add Me"></td><td>
      {% if msg %}
        <span style="color: #F00; text-align:left;">{{msg}}</span>
      {% endif %}
    </td>
    </tr><tr>
    </table>

    </p>
</form>
{% endblock %}

webapp/users/templates/users/settings.html
{% extends 'base.html' %}
{% block title %} Profile {% endblock %}
{% block h1 %} Profile of {{ request.user }}  {% endblock %}
{% block content %}
<!-- Modal for changing password -->
<div class="modal fade" id="changePassword" tabindex="-1" role="dialog" aria-labelledby="changePasswordLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true" class="glyphicon glyphicon-remove"></span>
        </button>
        <h4 class="modal-title" id="changePasswordLabel">Change password</h4>
      </div>
      <form class="form-horizontal" action="{% url 'users:change_password' %}" method="post">
        {% csrf_token %}
        <div class="modal-body">
          <div class="form-group">
            <label for="old_password" class="col-sm-4 control-label">Old password</label>
            <div class="col-sm-8">
              <input type="password" class="form-control" name="old_password" required>
            </div>
          </div>
          <div class="form-group">
            <label for="new_password1" class="col-sm-4 control-label">New password</label>
            <div class="col-sm-8">
              <input type="password" class="form-control" name="new_password1" required>
            </div>
          </div>
          <div class="form-group">
            <label for="new_password2" class="col-sm-4 control-label">Confirm new password</label>
            <div class="col-sm-8">
              <input type="password" class="form-control" name="new_password2" required>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
          <button type="submit" class="btn btn-primary">Change password</button>
        </div>
      </form>
    </div>
  </div>
</div>

<!-- Modal for changing email -->
<div class="modal fade" id="changeEmail" tabindex="-1" role="dialog" aria-labelledby="changeEmailLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true" class="glyphicon glyphicon-remove"></span>
        </button>
        <h4 class="modal-title" id="changeEmailLabel">Changing email</h4>
      </div>
      <form class="form-horizontal" action="{% url 'users:update_email' %}" method="post">
        {% csrf_token %}
        <div class="modal-body">
          <div class="form-group">
            <label class="col-sm-2 control-label">Old email</label>
            <div class="col-sm-10">
              <p class="form-control-static">{{ request.user.email }}</p>
            </div>
          </div>
          <div class="form-group">
            <label for="new_email" class="col-sm-2 control-label">New email</label>
            <div class="col-sm-10">
              <input type="email" class="form-control" name="new_email" placeholder="Email" required>
            </div>
          </div>
          <div class="form-group">
            <label for="password" class="col-sm-2 control-label">Password</label>
            <div class="col-sm-10">
              <input type="password" class="form-control" name="password" required>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
          <button type="submit" class="btn btn-primary">Change email</button>
        </div>
      </form>
    </div>
  </div>
</div>

<!-- Modal for invitation -->
<div class="modal fade" id="inviteUser" tabindex="-1" role="dialog" aria-labelledby="inviteUserLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true" class="glyphicon glyphicon-remove"></span>
        </button>
        <h4 class="modal-title" id="inviteUserLabel">Invite a new user</h4>
      </div>
      <form action="{% url 'users:newuser' %}" method="post">
        {% csrf_token %}
        <div class="modal-body">
          <label for="reason">Enter the email of the person you'd like to invite.</label>
          <input type="email" class="form-control" name="newuser" placeholder="Email" required>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
          <button type="submit" class="btn btn-primary">Invite</button>
        </div>
      </form>
    </div>
  </div>
</div>

<!-- Modal for absence -->
<div class="modal fade" id="setAbsent" tabindex="-1" role="dialog" aria-labelledby="setAbsentLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true" class="glyphicon glyphicon-remove"></span>
        </button>
        <h4 class="modal-title" id="setAbsentLabel">Long-term absence</h4>
      </div>
      <form action="{% url 'users:set_absent' %}" method="post">
        {% csrf_token %}
        <div class="modal-body">
          <label for="reason">Enter a reason for your absence.</label>
          <input type="text" class="form-control" name="reason" placeholder="Reason" required>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
          <button type="submit" class="btn btn-primary">Submit</button>
        </div>
      </form>
    </div>
  </div>
</div>

<!-- Modal for changing card -->
<div class="modal fade" id="changeCard" tabindex="-1" role="dialog" aria-labelledby="changeCardLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true" class="glyphicon glyphicon-remove"></span>
        </button>
        <h4 class="modal-title" id="changeCardLabel">Changing card</h4>
      </div>
      <form action="{% url 'users:update_card' %}" method="post">
        {% csrf_token %}
        <div class="modal-body">
          <label for="card_id">Select a card:</label>
          <select name="card_id" class="form-control">
            {% for card in cards %}
              <option value="{{ card.key }}">{{ card.key }}</option>
            {% endfor %}
          </select>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
          <button type="submit" class="btn btn-primary">Change card</button>
        </div>
      </form>
    </div>
  </div>
</div>

<!-- Modal for reporting a broken card -->
<div class="modal fade" id="reportBrokenCard" tabindex="-1" role="dialog" aria-labelledby="reportBrokenCardLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true" class="glyphicon glyphicon-remove"></span>
        </button>
        <h4 class="modal-title" id="reportBrokenCardLabel">Deleting</h4>
      </div>
      <div class="modal-body">
        <p>Are you sure you want to report your card as broken? This action is <strong>not</strong> reversible.</p>
      </div>
      <div class="modal-footer">
        <form action="{% url 'users:broken_card' %}" method="post">
          {% csrf_token %}
          <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
          <button type="submit" class="btn btn-danger">Report card</button>
        </form>
      </div>
    </div>
  </div>
</div>

<!-- Modal for deactivation -->
<div class="modal fade" id="deactivate" tabindex="-1" role="dialog" aria-labelledby="deactivateLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true" class="glyphicon glyphicon-remove"></span>
        </button>
        <h4 class="modal-title" id="deactivateLabel">Delete account</h4>
      </div>
      <form action="{% url 'users:deactivate' %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="reason" value="The user has left colemass">
        <div class="modal-body">
          <p>Are you sure you want to delete your account? This action is <strong>not</strong> reversible.</p>
          <label for="pswd">For security's sake, enter your password.</label>
          <input type="password" class="form-control" name="pswd" required>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
          <button type="submit" class="btn btn-danger">Delete account</button>
        </div>
      </form>
    </div>
  </div>
</div>

<div class="row main">
  <div class="row">
    <div class="col-md-12">
      <strong>Email:</strong> {{ request.user.email }}
      <button type="button" class="btn btn-default btn-sm" data-toggle="modal" data-target="#changeEmail">
        Change email
      </button>
      <button type="button" class="btn btn-default btn-sm" data-toggle="modal" data-target="#changePassword">
        Change password
      </button>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <strong>Card:</strong> {{ request.user.card }}
      <button type="button" class="btn btn-default btn-sm" data-toggle="modal" data-target="#changeCard">
        Change card
      </button>
      <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#reportBrokenCard">
        Report broken
      </button>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#setAbsent">
        Absence
      </button>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#inviteUser">
        Invite new user
      </button>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#deactivate">
        Delete account
      </button>
    </div>
  </div>
</div>
{% endblock %}

webapp/users/templates/users/setup.html
{% extends 'registration/base.html' %}
{% block title %}Setup{% endblock %}
{% block content %}
<div class="row main">
  <form method="post" action="{% url 'setup' %}" class="user-form">
    <h2>Welcome to Colemass</h2>
    <p>Please chose a username, email, password and card.</p>
      {% csrf_token %}
      <label for="id_username" class="sr-only">Username</label>
      <input type="text" id="id_username" name="username" class="form-control input-top input-lg" placeholder="Username" required autofocus>
      <label for="id_email" class="sr-only">Email</label>
      <input type="email" id="id_email" name="email" class="form-control input-middle input-lg" placeholder="Email" required>
      <label for="id_password" class="sr-only">Password</label>
      <input type="password" id="id_password" name="password" class="form-control input-middle input-lg" placeholder="Password" required>
      <label for="id_password2" class="sr-only">Confirm password</label>
      <input type="password" id="id_password2" name="password2" class="form-control input-bottom input-lg" placeholder="Confirm password" required>
      <div class="form-horizontal">
        <div class="form-group">
          <label class="col-sm-4 control-label" for="card_key">Select a card:</label>
          <div class="col-sm-8">
            <select name="card_key" class="form-control" required>
              {% for card in cards %}
                <option value="{{ card.key }}">{{ card.key }}</option>
              {% endfor %}
            </select>
          </div>
        </div>
      </div>
      <button class="btn btn-lg btn-primary btn-block" type="submit">Sign up</button>
  </form>
</div>
{% endblock %}