webapp/appliances/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'^$', views.appliances, name='appliances'),
    url(r'report/$', views.appliance_report, name='report'),
    url(r'getappliancestatus/(?P<hardwareId>\w+)/$', views.getApplianceStatus),
    url(r'getusername/(?P<cardID>\w+)/$', views.getUserName),
]

webapp/chores/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from . import views

urlpatterns = [
    url(r'^$', views.chores, name="chores"),
    url(r'^stats/$', views.stats, name='stats'),
    url(r'^done/$', views.done, name="done"),
    url(r'^nudge/$', views.nudge, name="nudge"),
    url(r'^completion/approve/$', views.completed_chore_approve, name="approve completion"),
    url(r'^completion/challenge/$', views.completed_chore_challenge, name="challenge completion"),
    url(r'^refuse/$', views.refuse, name="refuse"),
    url(r'^refusal/approve/$', views.refusal_approve, name="approve refusal"),
    url(r'^refusal/challenge/$', views.refusal_challenge, name="challenge refusal"),
    url(r'^settings/$', login_required(views.RecurringChoreListView.as_view()), name="settings"),
    url(r'^edit/$', views.edit, name="edit"),
    url(r'^new/$', views.new, name="new"),
    url(r'^delete/$', views.delete, name="delete"),
    
]

webapp/colemass/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.template import RequestContext
from django.contrib.auth import views as auth_views

from chores.views import mycolemass, stats
from users.views import setup, start, settings

authentication_urls = [
    url(r'^start/$', start, name='start'),
    url(r'^setup/$', setup, name='setup'),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout_then_login, name='logout'),
    url(r'^password-reset/$', auth_views.password_reset, {'post_reset_redirect': 'login'}, name='password_reset'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', auth_views.password_reset_confirm, {'post_reset_redirect': 'login'}, name='password_reset_confirm'),
#    url(r'password_change_done', settings, name='password_change_done')
#    url('^change-password/', auth_views.password_change, {'template_name': 'change-password.html', 'post_change_redirect': '/users/settings/'})
]

urlpatterns = [
    url(r'^$', mycolemass, name="mycolemass"),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^dishes/', include('dishes.urls', namespace="dishes")),
    url(r'^appliances/', include('appliances.urls', namespace="appliances")),
    url(r'^stats/', stats, name="stats"),
    url(r'^chores/', include('chores.urls', namespace="chores")),
    url(r'^user/', include('users.urls', namespace="users")),
    url(r'^hw/', include('hardware.urls', namespace="hardware")),
] + authentication_urls

def handler404(request):
    response = render_to_response('error404.html', {},
                                  context_instance=RequestContext(request))
    response.status_code = 404
    return response


def handler500(request):
    response = render_to_response('error404.html', {},
                                  context_instance=RequestContext(request))
    response.status_code = 500
    return response

def handler403(request):
    response = render_to_response('error404.html', {},
                                  context_instance=RequestContext(request))
    response.status_code = 403
    return response

webapp/dishes/urls.py
from django.conf.urls import url
from . import views

app_name = 'dishes'

urlpatterns = [
    url(r'^$', views.dishList, name='dishlist'),

    url(r'^mine$', views.myDishes, name='mydishes'),

    url(r'^editdish$', views.editDish, name='editdish'),

    url(r'^log$', views.dishLog, name='dishlog'),

    url(r'^new$', views.newDish, name='newdish'),

    url(r'^remove/(?P<dish_id>\d+)$', views.rmvDish, name='rmvdish'),

    url(r'^newchore$', views.newDishChore, name='newdishchore'),
]

webapp/hardware/urls.py
from django.conf.urls import url
from . import views

app_name = 'hardware'

urlpatterns = [
    # Get Card List
    url(r'^gcl$', views.gcl),

    # return one time pad for message encryption
    url(r'^getotp/(?P<hardwareId>\w+)$', views.getOTP),

    # challenge server, server should return hash of randomBytes
    # and a password of hadrware with hwid = hadrwareId
    url(r'^c/(?P<hardwareId>\w+)/(?P<randomBytes>[0-9a-f]+)$',
        views.responseToChallenge),

    # m = 'encrypted command message' request from hardware
    url(r'^m/(?P<hardwareId>\w+)/(?P<msg>(?:[A-Za-z0-9-_]{4})*(?:[A-Za-z0-9-_]{2}==|[A-Za-z0-9-_]{3}=)?)$',
        views.processMessage),

    url(r'^$', views.hwList, name='hwlist'),
    url(r'^new$', views.newHw, name='newhw'),
    url(r'^remove/(?P<hw_id>\d+)$', views.rmvHw, name='removehw'),
]

webapp/users/urls.py
from django.conf.urls import url
from . import views, registrationviews, settingsviews


urlpatterns = [
    url(r'^settings/$', views.settings, name='settings'),
    url(r'^broken_card/$', settingsviews.cardbroken, name='broken_card'),
    url(r'^update_card/$', settingsviews.cardupdate, name='update_card'),
    url(r'^deactivate/$', settingsviews.deactivate, name='deactivate'),
    url(r'^update_email/$', settingsviews.emailupdate, name='update_email'),
    url(r'^newuser/$', settingsviews.newuser, name='newuser'),
    url(r'^change_password/$', settingsviews.change_password, name='change_password'),
    url(r'^change_username/$', settingsviews.change_username, name='change_username'),
    url(r'^register/(?P<user>.*@\w+.\w+)/(?P<valid_key>\w+)/$', registrationviews.createuserform),
    url(r'^registeruser/$', registrationviews.registeruser, name='registeruser'),
    url(r'^set_absent/$', settingsviews.set_absent, name='set_absent'),
    url(r'^set_present/$', settingsviews.set_present, name='set_present'),
    url(r'^come_back/$', settingsviews.come_back, name='come_back'),
]

webapp/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <link rel="shortcut icon" href="{% static 'images/c.ico' %}" type="image/x-icon"/ >
    <title>{% block title %}{% endblock %} - COLEMASS</title>
  </head>
  <body>
    <div class="container">
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'mycolemass' %}"><img alt="Colemass" src="{% static 'images/colemass.svg' %}"></a>
          </div>        
          <div class="collapse navbar-collapse" id="navbar">
            <ul class="nav navbar-nav">
              <li><a href="{% url 'mycolemass' %}">My Colemass</a></li>
              <li><a href="{% url 'chores:chores' %}">Chores</a></li>
              <li><a href="{% url 'appliances:appliances' %}">Appliances</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li><a href="{% url 'stats' %}"><span class="glyphicon glyphicon-stats"></span> Statistics</a></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                  <span class="glyphicon glyphicon-cog"></span> Settings <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                  <li><a href="{% url 'users:settings' %}"><span class="glyphicon glyphicon-user"></span> Profile</a></li>
                  <li role="separator" class="divider"></li>
                  <li><a href="{% url 'dishes:dishlist' %}">Dish settings</a></li>
                  <li><a href="{% url 'chores:settings' %}">Chore settings</a></li>
                  <li><a href="{% url 'hardware:hwlist' %}">Hardware settings</a></li>
                </ul>
              </li>
              <li><a href="{% url 'logout' %}"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
            </ul>
          </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
      </nav>
      
      <div class="container-fluid">
        {% if request.user.userdetail.is_absent %}
          <form action="{% url 'users:come_back' %}"><input type="submit" class="btn btn-lg btn-primary btn-block" value="Click if you are back!"></form>
        {% else %}
          <div class="row">
            <h1 class="page-header">{% block h1 %}Title here{% endblock %}</h1>
            {% for message in messages %}
              <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true" class="glyphicon glyphicon-remove"></span>
                </button>
                {{ message }}
              </div>
            {% endfor %}
          </div>
          {% block content %}{% endblock %}
        {% endif %}
      </div>
    </div>
    <script src="{% static 'js/jquery-1.12.0.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/colemass.js' %}"></script>
  </body>
</html>

webapp/templates/change-password.html
{% extends 'registration/base.html' %}
{% block title %}Reset password{% endblock %}

{% block content %}
    <form method="post" class="user-form">
        {% csrf_token %}
        {{form}}
        <button class="btn btn-lg btn-primary btn-block" type="submit">Submit</button>
    </form>
{% endblock %}