webapp/colemass/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.template import RequestContext
from django.contrib.auth import views as auth_views

from chores.views import mycolemass, stats
from users.views import setup, start, settings

authentication_urls = [
    url(r'^start/$', start, name='start'),
    url(r'^setup/$', setup, name='setup'),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout_then_login, name='logout'),
    url(r'^password-reset/$', auth_views.password_reset, {'post_reset_redirect': 'login'}, name='password_reset'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', auth_views.password_reset_confirm, {'post_reset_redirect': 'login'}, name='password_reset_confirm'),
#    url(r'password_change_done', settings, name='password_change_done')
#    url('^change-password/', auth_views.password_change, {'template_name': 'change-password.html', 'post_change_redirect': '/users/settings/'})
]

urlpatterns = [
    url(r'^$', mycolemass, name="mycolemass"),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^dishes/', include('dishes.urls', namespace="dishes")),
    url(r'^appliances/', include('appliances.urls', namespace="appliances")),
    url(r'^stats/', stats, name="stats"),
    url(r'^chores/', include('chores.urls', namespace="chores")),
    url(r'^user/', include('users.urls', namespace="users")),
    url(r'^hw/', include('hardware.urls', namespace="hardware")),
] + authentication_urls

def handler404(request):
    response = render_to_response('error404.html', {},
                                  context_instance=RequestContext(request))
    response.status_code = 404
    return response


def handler500(request):
    response = render_to_response('error404.html', {},
                                  context_instance=RequestContext(request))
    response.status_code = 500
    return response

def handler403(request):
    response = render_to_response('error404.html', {},
                                  context_instance=RequestContext(request))
    response.status_code = 403
    return response

webapp/dishes/urls.py
from django.conf.urls import url
from . import views

app_name = 'dishes'

urlpatterns = [
    url(r'^$', views.dishList, name='dishlist'),

    url(r'^mine$', views.myDishes, name='mydishes'),

    url(r'^editdish$', views.editDish, name='editdish'),

    url(r'^log$', views.dishLog, name='dishlog'),

    url(r'^new$', views.newDish, name='newdish'),

    url(r'^remove/(?P<dish_id>\d+)$', views.rmvDish, name='rmvdish'),

    url(r'^newchore$', views.newDishChore, name='newdishchore'),
]

webapp/users/urls.py
from django.conf.urls import url
from . import views, registrationviews, settingsviews


urlpatterns = [
    url(r'^settings/$', views.settings, name='settings'),
    url(r'^broken_card/$', settingsviews.cardbroken, name='broken_card'),
    url(r'^update_card/$', settingsviews.cardupdate, name='update_card'),
    url(r'^deactivate/$', settingsviews.deactivate, name='deactivate'),
    url(r'^update_email/$', settingsviews.emailupdate, name='update_email'),
    url(r'^newuser/$', settingsviews.newuser, name='newuser'),
    url(r'^change_password/$', settingsviews.change_password, name='change_password'),
    url(r'^change_username/$', settingsviews.change_username, name='change_username'),
    url(r'^register/(?P<user>.*@\w+.\w+)/(?P<valid_key>\w+)/$', registrationviews.createuserform),
    url(r'^registeruser/$', registrationviews.registeruser, name='registeruser'),
    url(r'^set_absent/$', settingsviews.set_absent, name='set_absent'),
    url(r'^set_present/$', settingsviews.set_present, name='set_present'),
    url(r'^come_back/$', settingsviews.come_back, name='come_back'),
]

webapp/dishes/views.py
from django.shortcuts import render,  get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseBadRequest
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.contrib import messages
from .models import *

@login_required
def dishList(request):
    return render(request, 'dishes/dishlist.html', {'dishes': Dish.objects.all()})

@login_required
def myDishes(request,):
    dishes = Dish.getUserDishes(request.user)
    return render(request, 'dishes/mydishes.html', {'dishes': dishes})

@login_required
def dishLog(request):
    dish_id=request.POST.get('dish_id')
    ent = DishLog.getDishUsageLog(dish_id, 10)
    usr = []
    btns = [False] * len(ent)
    entries = zip(ent,btns)

    for i in range(len(ent)):
        if not ent[i].getTakeUser() in usr:
            usr.append(ent[i].getTakeUser())
            btns[i]=True
        elif not ent[i].getPutUser() in usr:
            usr.append(ent[i].getPutUser())
            btns[i]=True

    return render(request, 'dishes/dishlog.html', {'entries': entries})

@login_required
def newDish(request):
    if request.POST:
        ud = UnregisteredDish.objects.filter(
            pk__in=request.POST.getlist('checkdish'))
        if len(ud) == 0:
            messages.info(request, 'Please select at least 1 dish.')
        else:
            s = ''
            from django.db import IntegrityError
            try:
                import re
                for d in ud:
                    txt_Title = request.POST.get('title_' + str(d.id))
                    reg = re.compile(r'^[\w\s]+$')
                    if reg.search(txt_Title) is None:
                        messages.info(request, 'Please use only alphanumeric symbols and whitespaces to name dish.')
                        return render(request, 'dishes/newdish.html', {'dishes': UnregisteredDish.objects.all()})
                    d.registerDish(txt_Title)
                    s += '\"%s\" ' % d.getTitle()
            except IntegrityError:
                messages.error(request, 'Dish with tag already exists.')
            else:
                messages.info(request, s + 'were successfully registered.')
                return redirect('dishes:dishlist')

    return render(request, 'dishes/newdish.html', {'dishes': UnregisteredDish.objects.all()})


@login_required
def editDish(request):
    dish_id=request.POST.get('dish_id')
    dish = get_object_or_404(Dish, pk=dish_id)
    if request.POST:
        if 'btn_save' in request.POST:
            import re
            txt_Title = request.POST.get('txt_Title')
            reg = re.compile(r'^[\w\s]+$')
            if reg.search(txt_Title) is None:
                messages.info(request, 'Please   use only alphanumeric symbols and whitespaces to name dish.')
                return render(request, 'dishes/editdish.html', {'dish': dish})
            dish.setTitle(txt_Title)
            dish.save()
            return redirect('dishes:dishlist')
        if 'btn_rmv' in request.POST:
            return redirect(reverse('dishes:rmvdish', args=[dish.id]))
        else:
            return render(request, 'dishes/editdish.html', {'dish': dish})


@login_required
def rmvDish(request, dish_id):
    dish = get_object_or_404(Dish, pk=dish_id)
    if request.POST:
        dish.delete()
        messages.info(request, '%s was successfully deleted.' %
                      dish.getTitle())
        return redirect('dishes:dishlist')
    else:
        return render(request, 'dishes/rmvdish.html', {'dish': dish})

@login_required
def newDishChore(request):
    from django.contrib.auth.models import User

    reported_user = None
    dish_log = get_object_or_404(DishLog, pk=request.POST.get('entry_id'))
    user_radio = request.POST.get('usrlist')
    message = request.POST.get('txt_message')
    active_chores = DishChore.objects.filter(dish=dish_log.dish, active=True)
    
    if message:
        message = message.strip()
    if request.POST:
        if active_chores:
            messages.info(request, 'A dish chore for this dish is already existing.')
            return redirect('dishes:dishlist')
        if ((dish_log.taken_by != request.user) and
            (dish_log.returned_by != request.user) and
            (dish_log.taken_by != dish_log.returned_by) and
            (dish_log.returned_by is not None)):
            if user_radio is not None:
                reported_user = (dish_log.taken_by, dish_log.returned_by)[int(user_radio)]
            else:
                messages.info(request, 'Please select an assignee')
        elif (dish_log.taken_by != request.user):
            reported_user = dish_log.taken_by
        elif (dish_log.returned_by != request.user):
            reported_user = dish_log.returned_by
        else:
            return HttpResponseBadRequest()
        
        if not message:
            messages.info(request, 'Please leave a message')
        
        if message and reported_user:
            DishChore.create_new(
                initiator = request.user,
                assignee = reported_user,
                dish = dish_log.dish,
                message = message
                )
            messages.info(request, 'Dish chore successfully added.')
            return redirect('dishes:dishlist')
        else:
            user_list = []
            for user in {dish_log.taken_by, dish_log.returned_by}:
                if (user != request.user) and (user is not None):
                    user_list.append(user)
            
            if not user_list:
                return HttpResponseBadRequest()
            else:
                context = {
                    'dish': dish_log.dish,
                    'usr': user_list,
                    'entry_id': dish_log.pk,
                    }
                return render(request, 'dishes/newdishchore.html', context)
    else:
        return HttpResponse(3)

webapp/dishes/templates/dishes/dishlist.html
{% extends 'base.html' %}
{% load humanize %}
{% block title %}Dish list{% endblock %}
{% block h1 %} Dish list{% endblock %}
{% block content %}
<table width="150px">
  <tr>
    <td>
      <a href="{% url 'dishes:dishlist' %}">Dish list</a>
    </td>
    <td>
      <a href="{% url 'dishes:newdish' %}">New dish</a>
    </td>
  </tr>
</table>
  <div class="subpointlist">
    <table class='tab'>
      {% for dish in dishes %}
      <tr>
        <td>{{ dish.getTitle }}</td>
        <td>
          {% if dish.isTakenOut %}
          was taken out
          {% if dish.getAssignee %}
          by {{ dish.getAssignee }}
          {% endif %}
          {% else %}
          was returned in the Cupboard
          {% endif %}{{ dish.getLastUpdateTime|naturaltime }}
        </td>
        <td>
          <form action="{% url 'dishes:editdish' %}" method="post" >
            {% csrf_token %}
            <input type="hidden" name="dish_id" value="{{ dish.id }}">
            <input type="submit" value="Edit">
          </form>
        </td>
        <td>
          <form action="{% url 'dishes:dishlog' %}" method="post" >
            {% csrf_token %}
            <input type="hidden" name="dish_id" value="{{ dish.id }}">
            <input type="submit" value="Log">
          </form>
        </td>
      </tr>
      {% endfor %}
    </table>
 </div>
{% endblock %}

webapp/dishes/templates/dishes/dishlog.html
{% extends 'base.html' %}
{% load humanize %}
{% block title %}Usage log for{% endblock %}
{% block h1 %} Usage log for{% endblock %}
{% block content %}
<table width="150px">
  <tr>
    <td>
      <a href="{% url 'dishes:dishlist' %}">Dish list</a>
    </td>
    <td>
      <a href="{% url 'dishes:newdish' %}">New dish</a>
    </td>
  </tr>
</table>
  <div class="subpointlist">
    <table>
      <tr>
        <td colspan="2" align="center" width="200px">Taken out</td>
        <td colspan="2" align="center" width="200px">Put back</td>
      </tr>
      <tr>
        <td>User</td>
        <td>Time</td>
        <td>User</td>
        <td>Time</td>
        <td></td>
      </tr>
      {% for entry, btns in entries %}
      <tr>
        <td>{{ entry.getTakeUser }}</td>
        <td>{{ entry.getTakeTime|date:'H:i, d M' }}</td>
        {% if entry.getPutUser %}
        <td>{{ entry.getPutUser }}</td>
        <td>{{ entry.getPutTime|date:'H:i, d M' }}</td>
        {% else %}
        <td></td>
        <td></td>
        {% endif %}
        {% if request.user != entry.getTakeUser or request.user != entry.getPutUser and entry.getPutUser != None %}
        {% if btns%}
        <td>
          <form action="{% url 'dishes:newdishchore' %}" method="post" >
          {% csrf_token %}
            <input type="hidden" name="entry_id" value="{{ entry.id }}">
            <input type="submit" value="Report">
          </form>
        </td>
        {% endif %}
        {% endif %}
      </tr>
      {% endfor %}
    </table>
 </div>
{% endblock %}

webapp/dishes/templates/dishes/editdish.html
{% extends 'base.html' %}
{% block title %} Edit dish:&nbsp; {{dish.getTitle}}{% endblock %}
{% block h1 %} Edit dish:&nbsp; {{dish.getTitle}}{% endblock %}
{% block content %}
<table width="150px">
  <tr>
    <td>
      <a href="{% url 'dishes:dishlist' %}">Dish list</a>
    </td>
    <td>
      <a href="{% url 'dishes:newdish' %}">New dish</a>
    </td>
  </tr>
</table>
<div class="subpointlist">
  <form action="{% url 'dishes:editdish'%}" method="post">
    <input type="hidden" name="dish_id" value="{{ dish.id }}">
    <input type="hidden" value="{{ csrf_token }}" name="csrfmiddlewaretoken">
    <table>
      <tr>
        <td>Tag:</td>
        <td>{{dish.getTag}}</td>
      </tr>
      <tr>
        <td>Title:</td>
        <td><input type="text" name="txt_Title" id="txt_Title" value="{{dish.getTitle}}"/></td>
      </tr>
      <tr>
        <td align="right"><br><input type="submit" name='btn_rmv' value="Remove"></td>
        <td align="right"><br><input type="submit" name='btn_save' value="Save"></td>
      </tr>
    </table>
  </form>
  <br/>
</div>
{% endblock %}

webapp/dishes/templates/dishes/mydishes.html
{% extends 'base.html' %}
{% load humanize %}
{% block title %} Dish list {% endblock %}
{% block h1 %} Dish list {% endblock %}
{% block content %}
<table width="150px">
  <tr>
    <td>
      <a href="{% url 'dishes:dishlist' %}">Dish list</a>
    </td>
    <td>
      <a href="{% url 'dishes:newdish' %}">New dish</a>
    </td>
  </tr>
</table>
  <div class="subpointlist">
{% if dishes %}
  <table cellpadding="10px">
    <tr>
      <td>Title</td>
      <td>Take time</td>
      <td></td>
      <td></td>
    </tr>
    {% for dish in dishes %}
    <tr>
      <td>{{ dish.getTitle }}</td>       
      <td>{{ dish.getLastUpdateTime|naturaltime }}</td>
      <td><a style="text-align:center" href="{% url 'dishes:editdish' dish.id %}">Edit</a></td>
      <td><a style="text-align:center" href="{% url 'dishes:dishlog' dish.id %}">Log</a></td>
    </tr>
    {% endfor %}
  </table>
{% else %}
<span>There are no dishes assigned to you.</span>
{% endif %}
</div>
{% endblock %}

webapp/dishes/templates/dishes/newdish.html
{% extends 'base.html' %}
{% load humanize %}
{% block title %} Register new dishes {% endblock %}
{% block h1 %} Register new dishes {% endblock %}
{% block content %}
<table width="150px">
  <tr>
    <td>
      <a href="{% url 'dishes:dishlist' %}">Dish list</a>
    </td>
    <td>
      <a href="{% url 'dishes:newdish' %}">New dish</a>
    </td>
  </tr>
</table>
<div class="subpointlist">
  <form action="{% url 'dishes:newdish' %}" method="post">
  <input type="hidden" value="{{ csrf_token }}" name="csrfmiddlewaretoken">
  <table width="600px">
    <tr>
      <td>Check</td>
      <td>Tag</td>
      <td>Title</td>
      <td>Detection time</td>
    </tr>    
{% for dish in dishes %}
    <tr>
      <td><input type="checkbox" name="checkdish" value="{{dish.id}}"></td>
      <td>{{dish.getTag}}</td>
      <td><input type="text" name="title_{{dish.id}}" value="{{dish.getTitle}}"/></td>
      <td>{{dish.getDetectionTime|naturaltime}}</td>
    </tr>
{% endfor %}
    <tr>
      <td></td>
      <td></td>
      <td></td>
      <td><br><input type="submit" name="submit" value="Register"></td>
    </tr>     
  </table>
  </form>
  <br/>
</div>
{% endblock %}

webapp/dishes/templates/dishes/newdishchore.html
{% extends 'base.html' %}
{% load humanize %}
{% block title %} Dish list {% endblock %}
{% block h1 %} Dish list {% endblock %}
{% block content %}
<table width="150px">
  <tr>
    <td>
      <a href="{% url 'dishes:dishlist' %}">Dish list</a>
    </td>
    <td>
      <a href="{% url 'dishes:newdish' %}">New dish</a>
    </td>
  </tr>
</table>
  <div class="subpointlist">

  <form action="" method="post">
  <input type="hidden" value="{{ csrf_token }}" name="csrfmiddlewaretoken">
  <table width="300px">
    <tr>
      <td>Dish:</td>
      <td>{{ dish.getTitle }}</td>
    </tr>
    <tr>
      <td>Assignee:</td>
      {% if usr|length == 1 %}
      <td>{{ usr.0.username }}</td>
      {% elif usr|length == 2 %}
      <td>
        <input type="radio" name="usrlist" id="rb_0" value="0">
        <label for="rb_0">{{usr.0.username}}</label><br>
        <input type="radio" name="usrlist" id="rb_0" value="1">
        <label for="rb_1">{{usr.1.username}}</label>
      </td>
      {% endif %}
    </tr>
    <tr>
      <td>Message:</td>
      <td><textarea name="txt_message" maxlength="50" placeholder="Message"></textarea></td>
    </tr>
    <tr>
      <td></td>
      <td><br>
      <input type="hidden" name="entry_id" value="{{ entry_id }}">
<input type="submit" name="submit" value="Create chore"></td>
    </tr>
  </table>
  </form>
 </div>
{% endblock %}

webapp/dishes/templates/dishes/rmvdish.html
{% extends 'base.html' %}
{% block title %} Remove {{dish.getTitle}} {% endblock %}
{% block h1 %} Remove {{dish.getTitle}} {% endblock %}
{% block content %}
<table width="150px">
  <tr>
    <td>
      <a href="{% url 'dishes:dishlist' %}">Dish list</a>
    </td>
    <td>
      <a href="{% url 'dishes:newdish' %}">New dish</a>
    </td>
  </tr>
</table>
<div class="subpointlist">
  <form action="{% url 'dishes:rmvdish' dish.id %}" method="post">
  <input type="hidden" value="{{ csrf_token }}" name="csrfmiddlewaretoken">
    <table>
      <tr>
        <td><span>Are you sure you want to remove {{dish.getTitle}}? The operation can't be undone.</span></td> 
      </tr>
      <tr>
        <td align="right"><br><input type="submit" name="submit" value="Remove"></td> 
      </tr>
    </table>
  </form>
  <br/>
</div>
{% endblock %}