webapp/chores/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from . import views

urlpatterns = [
    url(r'^$', views.chores, name="chores"),
    url(r'^stats/$', views.stats, name='stats'),
    url(r'^done/$', views.done, name="done"),
    url(r'^nudge/$', views.nudge, name="nudge"),
    url(r'^completion/approve/$', views.completed_chore_approve, name="approve completion"),
    url(r'^completion/challenge/$', views.completed_chore_challenge, name="challenge completion"),
    url(r'^refuse/$', views.refuse, name="refuse"),
    url(r'^refusal/approve/$', views.refusal_approve, name="approve refusal"),
    url(r'^refusal/challenge/$', views.refusal_challenge, name="challenge refusal"),
    url(r'^settings/$', login_required(views.RecurringChoreListView.as_view()), name="settings"),
    url(r'^edit/$', views.edit, name="edit"),
    url(r'^new/$', views.new, name="new"),
    url(r'^delete/$', views.delete, name="delete"),
    
]

webapp/colemass/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.template import RequestContext
from django.contrib.auth import views as auth_views

from chores.views import mycolemass, stats
from users.views import setup, start, settings

authentication_urls = [
    url(r'^start/$', start, name='start'),
    url(r'^setup/$', setup, name='setup'),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout_then_login, name='logout'),
    url(r'^password-reset/$', auth_views.password_reset, {'post_reset_redirect': 'login'}, name='password_reset'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', auth_views.password_reset_confirm, {'post_reset_redirect': 'login'}, name='password_reset_confirm'),
#    url(r'password_change_done', settings, name='password_change_done')
#    url('^change-password/', auth_views.password_change, {'template_name': 'change-password.html', 'post_change_redirect': '/users/settings/'})
]

urlpatterns = [
    url(r'^$', mycolemass, name="mycolemass"),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^dishes/', include('dishes.urls', namespace="dishes")),
    url(r'^appliances/', include('appliances.urls', namespace="appliances")),
    url(r'^stats/', stats, name="stats"),
    url(r'^chores/', include('chores.urls', namespace="chores")),
    url(r'^user/', include('users.urls', namespace="users")),
    url(r'^hw/', include('hardware.urls', namespace="hardware")),
] + authentication_urls

def handler404(request):
    response = render_to_response('error404.html', {},
                                  context_instance=RequestContext(request))
    response.status_code = 404
    return response


def handler500(request):
    response = render_to_response('error404.html', {},
                                  context_instance=RequestContext(request))
    response.status_code = 500
    return response

def handler403(request):
    response = render_to_response('error404.html', {},
                                  context_instance=RequestContext(request))
    response.status_code = 403
    return response

webapp/users/urls.py
from django.conf.urls import url
from . import views, registrationviews, settingsviews


urlpatterns = [
    url(r'^settings/$', views.settings, name='settings'),
    url(r'^broken_card/$', settingsviews.cardbroken, name='broken_card'),
    url(r'^update_card/$', settingsviews.cardupdate, name='update_card'),
    url(r'^deactivate/$', settingsviews.deactivate, name='deactivate'),
    url(r'^update_email/$', settingsviews.emailupdate, name='update_email'),
    url(r'^newuser/$', settingsviews.newuser, name='newuser'),
    url(r'^change_password/$', settingsviews.change_password, name='change_password'),
    url(r'^change_username/$', settingsviews.change_username, name='change_username'),
    url(r'^register/(?P<user>.*@\w+.\w+)/(?P<valid_key>\w+)/$', registrationviews.createuserform),
    url(r'^registeruser/$', registrationviews.registeruser, name='registeruser'),
    url(r'^set_absent/$', settingsviews.set_absent, name='set_absent'),
    url(r'^set_present/$', settingsviews.set_present, name='set_present'),
    url(r'^come_back/$', settingsviews.come_back, name='come_back'),
]

webapp/chores/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.mail import EmailMessage
from django.utils import timezone
from django.core.urlresolvers import reverse
from colemass import settings

import datetime, random

# These are the models pertaining to CHORES

NUDGE_DELAY = 10 #seconds
INFRACTION_THRESHOLD = 3 #nudges
STATISTICS_PERIOD = 30 #days

def random_order():
    users = User.objects.filter(is_active=True, userdetail__is_absent=False)
    return ','.join([str(user.pk) for user in sorted(users, key=lambda k: random.random())])

def random_user():
    users = User.objects.filter(is_active=True, userdetail__is_absent=False)
    return random.choice(users)

def a_long_time_ago():
    return timezone.now() - datetime.timedelta(days=100)


class Chore(models.Model):
    name = models.CharField(max_length=50)
    assignee = models.ForeignKey(User, blank=True, null=True, on_delete=models.SET_NULL)
    assigned_time = models.DateTimeField(default=timezone.now)
    nudges = models.SmallIntegerField(default=0)
    last_nudge = models.DateTimeField(default=a_long_time_ago)
    active = models.BooleanField(default=False)

    class Meta:
        ordering = ['-nudges', '-assigned_time']

    def __str__(self):
        return self.name

    def reset_nudges(self):
        ''' Resets nudges. '''
        self.nudges = 0
        self.last_nudge = a_long_time_ago()

    def assign(self, user):
        ''' Assigns chore to use. '''
        self.reset_nudges()
        self.active = True
        self.assignee = user
        self.assigned_time = timezone.now()
        self.save()

    def complete(self, user):
        ''' Completes assigned chore. '''
        # confirm previous unconfirmed completed chore
        for chore in CompletedChore.objects.filter(chore=self, confirmed=False):
            chore.confirmed = True
            chore.save()
        # confirm previous unconfirmed refused chore
        for chore in RefusedChore.objects.filter(chore=self, confirmed=False):
            chore.confirmed = True
            chore.save()
        # create new completed chore
        CompletedChore.objects.create(chore=self, user=user, nudges=self.nudges)

    def refuse(self, reason):
        ''' Refuses assigned chore. '''
        # confirm previous unconfirmed refused chore
        for chore in RefusedChore.objects.filter(chore=self, confirmed=False):
            chore.confirmed = True
            chore.save()
        # log refused chore
        RefusedChore.objects.create(chore=self, user=self.assignee, reason=reason)

    def report(self):
        '''
        Nudges assignee, possibly logs infraction. Emails relevant user.
        Returns a message to be displayed in the web app
        '''
        message = "It is too early to nudge {0} for \"{1}\"".format(self.assignee.username, self.name)
        if (timezone.now() - self.last_nudge) > datetime.timedelta(seconds=NUDGE_DELAY):
            # anti spam check
            self.nudges += 1
            self.last_nudge = timezone.now()
            self.save()
            if (self.nudges % INFRACTION_THRESHOLD == 0) and not (self.nudges == 0):
                # every three reports, log an infraction
                Infraction.objects.create(chore=self, user=self.assignee)

                from dishes.tasks import sendemail
                title = "[COLEMASS] Infraction"
                body = "Hi {0},\n\n An infraction has been logged " \
                    "for not completing \"{1}\".".format(self.assignee.username, self.name)
                sender = getattr(settings, "EMAIL_HOST_USER", 'colemass')
                to = [self.assignee.email, ]
                sendemail(title, body, sender, to)

                message = "{0} was nudged for \"{1}\" and an infraction was logged.".format(self.assignee.username, self.name)
            else:

                from dishes.tasks import sendemail
                title = "[COLEMASS] Friendly reminder"
                body = "Hi {0},\n\nYou have been nudged {1} time{2} " \
                "to complete the chore \"{3}\".".format(self.assignee.username, self.nudges, ('s','')[self.nudges==1], self.name)
                sender = getattr(settings, "EMAIL_HOST_USER", 'colemass')
                to = [self.assignee.email, ]
                sendemail(title, body, sender, to)

                message = "{0} was nudged for \"{1}\".".format(self.assignee.username, self.name)
        return message

class RecurringChore(Chore):
    round_robin = models.CharField(max_length=50, default=random_order, blank=True, null=True)

    def get_absolute_url(self):
        return reverse('chores:edit', kwargs={'pk': self.pk})

    def get_round_robin(self):
        ''' Round robin as list of int '''
        if self.round_robin:
            return [int(i) for i in self.round_robin.split(',')]
        else:
            return []

    def set_round_robin(self, id_list):
        ''' Updates round robin from list of int '''
        self.round_robin = ','.join([str(i) for i in id_list])

    def remove_from_round_robin(self, user):
        pk = user.pk
        order = self.get_round_robin()
        if pk in order:
            order.remove(pk)
        self.set_round_robin(order)

    def add_randomly_to_round_robin(self, user):
        pk = user.pk
        order = self.get_round_robin()
        if order:
            order.insert(random.randint(1,len(order)),pk)
        else:
            order = [pk]
        self.set_round_robin(order)

    def send_to_end(self, user):
        ''' Sends user at the end of round-robin. '''
        order = self.get_round_robin()
        order.remove(user.pk)
        order.append(user.pk)
        self.set_round_robin(order)
        super(RecurringChore, self).assign(User.objects.get(pk=order[0]))

    def complete(self, user):
        ''' Base chore completion + round-robin reassignment. '''
        super(RecurringChore, self).complete(user)
        self.send_to_end(user)

        from dishes.tasks import sendemail
        title = "[COLEMASS] Chore assignment"
        body = "Hi {0},\n\nThe chore \"{1}\" has been assigned to you.".format(self.assignee.username, self.name)
        sender = getattr(settings, "EMAIL_HOST_USER", 'colemass')
        to = [self.assignee.email, ]
        sendemail(title, body, sender, to)


    def refuse(self, reason):
        ''' Base chore refusal + round-robin reassignment. '''
        refusing_user = self.assignee
        super(RecurringChore, self).refuse(reason)
        self.send_to_end(self.assignee)
        print(self.assignee.username)
        print(self.name)
        print(refusing_user.username)

        from dishes.tasks import sendemail
        title = "[COLEMASS] Chore assignment"
        body = "Hi {0},\n\nThe chore \"{1}\" has been refused by {2} and it has been assigned to you.\nYou can challenge this assignment in your Colemass.".format(self.assignee.username, self.name, refusing_user.username)
        sender = getattr(settings, "EMAIL_HOST_USER", 'colemass')
        to = [self.assignee.email, ]
        sendemail(title, body, sender, to)

class CompletedChore(models.Model):
    chore = models.ForeignKey(Chore)
    user = models.ForeignKey(User)
    date = models.DateTimeField(auto_now_add=True)
    nudges = models.SmallIntegerField()
    confirmed = models.BooleanField(default=False)

    class Meta:
        ordering = ['-date']

    def __str__ (self):
        return self.chore.name

    def confirm(self):
        ''' Confirms completion log entry. '''
        self.confirmed = True
        self.save()

    def challenge(self):
        '''
        Reassigns the chore to the user claiming the completion,
        logs an infraction, deletes completion log entry.
        '''
        self.chore.assign(self.user)
        Infraction.objects.create(user=self.user, chore=self.chore)
        self.delete()


class RefusedChore(models.Model):
    chore = models.ForeignKey(Chore)
    user = models.ForeignKey(User)
    date = models.DateTimeField(auto_now_add=True)
    reason = models.CharField(max_length=140)
    confirmed = models.BooleanField(default=False)

    class Meta:
        ordering = ['-date']

    def __str__ (self):
        return self.chore.name

    def confirm(self):
        ''' Confirms refusal log entry. '''
        self.confirmed = True
        self.save()

    def challenge(self):
        '''
        Reassigns the chore to the user refusing it,
        logs an infraction, deletes refusal log entry.
        '''
        self.chore.assign(self.user)
        Infraction.objects.create(user=self.user, chore=self.chore)
        self.delete()


class Infraction(models.Model):
    user = models.ForeignKey(User)
    chore = models.ForeignKey(Chore)
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-date']

    def __str__ (self):
        return self.user.username

    def is_recent(self):
        return (timezone.now() - self.date) < datetime.timedelta(days=STATISTICS_PERIOD)
    is_recent.boolean = True

webapp/chores/forms.py
from django.forms import ModelForm
from .models import RecurringChore

class RecurringChoreForm(ModelForm):
    class Meta:
        model = RecurringChore
        fields = ['name', 'active']
        error_messages = {
            'name': {
                'required': "Please enter a chore name.",
            },
        }

webapp/chores/templates/chores/chores.html
{% extends 'base.html' %}
{% block title %} Chores {% endblock %}
{% block h1 %} Chores {% endblock %}
{% block content %}
<div class="row main">
  {% for chore in chores %}
    <div class="row div-hover">
      <div class="col-md-4 col-xs-12"><strong>{{ chore.name }}</strong></div>
      <div class="col-md-3 col-sm-6 col-xs-12">assigned {{ chore.assigned_time|timesince }} ago</div>
      <div class="col-md-3 col-sm-4 col-xs-6">to {% if chore.assignee == request.user %}you{% else %}{{ chore.assignee }}{% endif %}</div>
      <div class="col-md-1 col-sm-1 col-xs-3 text-right">
        <form action="{% url 'chores:done' %}" method="post">
          {% csrf_token %}
          <input type="hidden" name="pk" value="{{ chore.pk }}">
          <button type="submit" class="btn btn-success btn-xs" {% if "Automated message" in chore.name %}disabled{% endif %}>{% if chore.assignee == request.user %}Done{% else %}On me{% endif %}</input>
        </form>
      </div>
      <div class="col-md-1 col-sm-1 col-xs-3 text-right">
        <form action="{% url 'chores:nudge' %}" method="post">
          {% csrf_token %}
          <input type="hidden" name="pk" value="{{ chore.pk }}">
          <button type="submit" class="btn btn-primary btn-xs"  {% if chore.assignee == request.user %}disabled{% endif %}>Nudge</input>
        </form>
      </div>
    </div>
  {% empty %}
    <div class="row">
      <div class="col-md-12"><em>There are no active chores at the moment.</em></div>
    </div>
  {% endfor %}
</div>
{% endblock %}

webapp/chores/templates/chores/confirm_delete.html
{% extends 'base.html' %}
{% block content %}
<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm" />
</form>
{% endblock %}

webapp/chores/templates/chores/edit.html
{% extends 'base.html' %}
{% block content %}
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update" />
</form>
{% endblock %}

webapp/chores/templates/chores/mycolemass.html
{% extends 'base.html' %}
{% block title %} My Colemass {% endblock %}
{% block h1 %} My Colemass {% endblock %}
{% block content %}
<!-- Modal for chore refusal -->
<div class="modal fade" id="refusing" tabindex="-1" role="dialog" aria-labelledby="refusingLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true" class="glyphicon glyphicon-remove"></span>
        </button>
        <h4 class="modal-title" id="refusingLabel">Refusing</h4>
      </div>
      <form action="{% url 'chores:refuse' %}" method="post">
        {% csrf_token %}
        <div class="modal-body">
          <div class="form-group">
            <label for="reason">Reason for refusal</label>
            <input type="text" class="form-control" name="reason" placeholder="Reason" required>
            <input type="hidden" name="pk" value="0">
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
          <button type="submit" class="btn btn-danger">Refuse</button>
        </div>
      </form>
    </div>
  </div>
</div>

<!-- Main content -->
<div class="row main">
  {% if absent_users %}
    <div class="alert alert-info" role="alert">
      <strong>Absent user{{ absent_users|pluralize }}:</strong>
      {% for user in absent_users %}
        {{ user }}{% if forloop.last %}. {% else %}, {% endif %}
      {% endfor %}
    </div>
  {% endif %}
  <h2 class="sub-header">My Chores</h2>
  {% for chore in chores %}
    <div class="row div-hover">
      <div class="col-md-4 col-xs-12"><strong>{{ chore.name }}</strong></div>
      <div class="col-md-3 col-sm-6 col-xs-12">assigned {{ chore.assigned_time|timesince }} ago</div>
      <div class="col-md-3 col-sm-4 col-xs-6">{{ chore.nudges }} nudge{{ chore.nudges|pluralize }}</div>
      <div class="col-md-1 col-sm-1 col-xs-3 text-right">
        <form action="{% url 'chores:done' %}" method="post">
          {% csrf_token %}
          <input type="hidden" name="pk" value="{{ chore.pk }}">
          <button type="submit" class="btn btn-success btn-xs" {% if "Automated message" in chore.name %}disabled{% endif %}>Done</input>
        </form>
      </div>
      <div class="col-md-1 col-sm-1 col-xs-3 text-right">
        <button type="button" class="btn btn-danger btn-xs" {% if "Automated message" in chore.name %}disabled{% endif %} data-toggle="modal" data-target="#refusing"
          data-chorepk="{{ chore.pk }}" data-chorename="{{ chore.name }}">
          Refuse
        </button>
      </div>
    </div>
  {% empty %}
    <div class="row">
      <div class="col-md-12"><em>You don't have any chores at the moment.</em></div>
    </div>
  {% endfor %}
  
  <h2 class="sub-header">Completed chores</h2>
  {% for completed_chore in completed_chores %}
    <div class="row div-hover">
      <div class="col-md-4 col-xs-12"><strong>{{ completed_chore.chore.name }}</strong></div>
      <div class="col-md-3 col-sm-6 col-xs-12">completed by {{ completed_chore.user }}</div>
      <div class="col-md-3 col-sm-4 col-xs-6">{{ completed_chore.date|date:"D d M" }} at {{ completed_chore.date|time:"H:i" }}</div>
      <div class="col-md-1 col-sm-1 col-xs-3 text-right">
        <form action="{% url 'chores:approve completion' %}" method="post">
          {% csrf_token %}
          <input type="hidden" name="pk" value="{{ completed_chore.pk }}">
          <button type="submit" class="btn btn-success btn-xs" {% if completed_chore.user == request.user %}disabled{% endif %}>Confirm</input>
        </form>
      </div>
      <div class="col-md-1 col-sm-1 col-xs-3 text-right">
        <form action="{% url 'chores:challenge completion' %}" method="post">
          {% csrf_token %}
          <input type="hidden" name="pk" value="{{ completed_chore.pk }}">
          <button type="submit" class="btn btn-danger btn-xs"
            {% if completed_chore.user == request.user or not completed_chore.user.is_active or completed_chore.user.userdetail.is_absent %}
              disabled
            {% endif %}>Reject</input>
        </form>
      </div>
    </div>
  {% empty %}
    <div class="row">
      <div class="col-md-12"><em>No completed chores at the moment.</em></div>
    </div>
  {% endfor %}

  <h2 class="sub-header">Refused chores</h2>
  {% for refused_chore in refused_chores %}
    <div class="row div-hover">
      <div class="col-md-4 col-xs-12"><strong>{{ refused_chore.chore.name }}</strong></div>
      <div class="col-md-3 col-sm-6 col-xs-12">refused by {{ refused_chore.user }}</div>
      <div class="col-md-3 col-sm-4 col-xs-12">Reason: {{ refused_chore.reason }}</div>
      <div class="col-md-1 col-sm-1 col-xs-9 text-right">
        <form action="{% url 'chores:approve refusal' %}" method="post">
          {% csrf_token %}
          <input type="hidden" name="pk" value="{{ refused_chore.pk }}">
          <button type="submit" class="btn btn-success btn-xs" {% if refused_chore.user == request.user %}disabled{% endif %}>Confirm</input>
        </form>
      </div>
      <div class="col-md-1 col-sm-1 col-xs-3 text-right">
        <form action="{% url 'chores:challenge refusal' %}" method="post">
          {% csrf_token %}
          <input type="hidden" name="pk" value="{{ refused_chore.pk }}">
          <button type="submit" class="btn btn-danger btn-xs"
            {% if refused_chore.user == request.user or not refused_chore.user.is_active or refused_chore.user.userdetail.is_absent %}
              disabled
            {% endif %}>Reject</input>
        </form>
      </div>
    </div>
  {% empty %}
    <div class="row">
      <div class="col-md-12"><em>No refused chores at the moment.</em></div>
    </div>
  {% endfor %}
</div>
{% endblock %}

webapp/chores/templates/chores/new.html
{% extends 'base.html' %}
{% block content %}
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Create" />
</form>
{% endblock %}

webapp/chores/templates/chores/settings.html
{% extends 'base.html' %}
{% block title %} Recurring chore settings {% endblock %}
{% block h1 %} Recurring chore settings {% endblock %}
{% block content %}
<!-- Modal for chore creation -->
<div class="modal fade" id="newChore" tabindex="-1" role="dialog" aria-labelledby="newChoreLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true" class="glyphicon glyphicon-remove"></span>
        </button>
        <h4 class="modal-title" id="newChoreLabel">Creating a new recurring chore</h4>
      </div>
      <form class="form-horizontal" action="{% url 'chores:new' %}" method="post">
        {% csrf_token %}
        <div class="modal-body">
          {{ form.non_field_errors }}
          <div class="form-group">
            {{ form.name.errors }}
            <label for="{{ form.name.id_for_label }}" class="col-sm-2 control-label">Chore name</label>
            <div class="col-sm-10">
              <input type="text" class="form-control" name="name" placeholder="Chore name" required>
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <div class="checkbox">
                <label>
                  {{ form.active }} Active
                </label>
              </div>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
          <button type="submit" class="btn btn-primary">Create</button>
        </div>
      </form>
    </div>
  </div>
</div>

<!-- Modal for chore editing -->
<div class="modal fade" id="editChore" tabindex="-1" role="dialog" aria-labelledby="editChoreLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true" class="glyphicon glyphicon-remove"></span>
        </button>
        <h4 class="modal-title" id="editChoreLabel">Editing</h4>
      </div>
      <form class="form-horizontal" action="{% url 'chores:edit' %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="pk" value="0">
        <div class="modal-body">
          {{ form.non_field_errors }}
          <div class="form-group">
            {{ form.name.errors }}
            <label for="{{ form.name.id_for_label }}" class="col-sm-2 control-label">Chore name</label>
            <div class="col-sm-10">
              <input type="text" class="form-control" name="name" value="Chore name" required>
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <div class="checkbox">
                <label>
                  {{ form.active }} Active
                </label>
              </div>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
          <button type="submit" class="btn btn-primary">Update</button>
        </div>
      </form>
    </div>
  </div>
</div>

<!-- Modal for chore deleting -->
<div class="modal fade" id="deleteChore" tabindex="-1" role="dialog" aria-labelledby="deleteChoreLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true" class="glyphicon glyphicon-remove"></span>
        </button>
        <h4 class="modal-title" id="deleteChoreLabel">Deleting</h4>
      </div>
      <div class="modal-body">
        <p>Are you sure you want to delete this chore?</p>
      </div>
      <div class="modal-footer">
        <form action="{% url 'chores:delete' %}" method="post">
          {% csrf_token %}
          <input type="hidden" name="pk" value="0">
          <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
          <button type="submit" class="btn btn-danger">Delete</button>
        </form>
      </div>
    </div>
  </div>
</div>

<div class="row main">
  {% for chore in chores %}
    <div class="row div-hover">
      <div class="col-sm-4">
        <strong>{{ chore.name }}</strong>
      </div>
      <div class="col-sm-1 col-xs-6">
        {% if chore.active %}Active{% else %}Inactive{% endif %}
      </div>
      <div class="col-sm-1 col-xs-3 text-right">
        <button type="button" class="btn btn-default btn-xs" data-toggle="modal" data-target="#editChore"
          data-chorepk="{{ chore.pk }}" data-chorename="{{ chore.name }}" data-active="{{ chore.active }}">
          Edit
        </button>
      </div>
      <div class="col-sm-1 col-xs-3 text-right">
        <button type="button" class="btn btn-danger btn-xs" data-toggle="modal" data-target="#deleteChore"
          data-chorepk="{{ chore.pk }}" data-chorename="{{ chore.name }}"
          {% if chore.completedchore_set.all or chore.refusedchore_set.all%}disabled{% endif %}>
          Delete
        </button>
      </div>
    </div>
  {% empty %}
    <div class="row">
      <div class="col-md-12"><em>There are no recurring chores in the system.</em></div>
    </div>
  {% endfor %}
  <div class="row">
    <div class="col-md-12">
      <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#newChore">
        Create new
      </button>
    </div>
  </div>
</div>
{% endblock %}

webapp/chores/templates/chores/stats.html
{% extends 'base.html' %}
{% block title %} Stats {% endblock %}
{% block h1 %} Stats {% endblock %}
{% block content %}
<div class="row main">
  <h2 class="sub-header">Hall of fame <small>Users with the most completed chores</small></h2>
  <ul>
    {% for user in users_hof %}
      <li>{{ user }}: {{user.completedchore_set.count}}</li>
    {% endfor %}
  </ul>

  <h2 class="sub-header">Wall of shame <small>Users with the most infractions</small></h2>
  <ul>
    {% for user in users %}
      <li>{{ user }}: {{ user.infraction_set.count }}</li>
    {% endfor %}
  </ul>
</div>
{% endblock %}